config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  get 'sign_in' => 'sessions#new'

  get 'index' => 'home#index'
  delete 'sign_out' => 'sessions#destroy'
  resources :messages
  root 'home#index'


 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  def sender
    @user ||= User.find_by(id: sender_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  #has_many :received_messages, class: "Message", foreign_key: :recipient_id
  def received_messages
    Message.where(recipient_id: id)
  end

  def sent_messages
    Message.where(sender_id: id)
  end

  # def to_s
  #   "#{name}:#{email}"
  # end
  #
  def unread_messages
    received_messages.where(is_read: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
#  before_action :authenticate_user, except: [:new]
  helper_method :current_user

  def current_user
    # return @current_user if @current_user.present?

    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def authenticate_user
    if session.has_key?(:user_id)
      # do nothing
    else
      redirect_to new_session_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to messages_path
    else
      redirect_to users_path
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

#  skip_before_action :authenticate_user, only: [:new]

  def index
    @messages = current_user.received_messages
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if @user = User.find_by(email: params[:email])
      if @user.authenticate(params[:password])
        flash[:success] = "Signed in successfully."
        session[:user_id] = @user.id
        redirect_to messages_path

      else
        flash.now[:error] = "Wrong Password."
        render 'new'
      end
    else
      flash.now[:error] = "User not Found"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: {success: "You Are Signed Out"}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.shuffle
  end
  
  def new
    @user = User.new(email: params[:email])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome #{@user.name}"
      # assign session to keep login for register user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # file: application_helper.rb
  def bootstrap_class_for flash_type
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-warning'}[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.map do |msg_type, message|
      content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade show") do
        content_tag(:button, '&times'.html_safe, class: 'close', data: {dismiss: 'alert'}) + message
      end
    end.join.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome minichat</h1>

<% if current_user.present? %>
  Welcome <%= current_user.name %>
<% else %>
  <%= link_to "Sign Up", new_user_path, class: 'btn btn-secondary' %>
  <%= link_to "Sign In", new_session_path, class: 'btn btn-secondary' %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">Home</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if current_user.present? %>
        <li class="nav-item">
          <%= link_to "Sign Out", sign_out_path, method:'delete', class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Sign In", new_session_path, class: 'nav-link' %>

        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_path, class: 'nav-link' %>
        </li>
      <% end %>

      <li class="nav-item">
        <%= link_to "All People", users_path, class: 'nav-link' %>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phuonghoang713chat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<h1> Messages</h1>
<table class="table table-stripped">
  <thred class="thread thread-default">
    <tr>
      <th>
        Sender
      </th>
      <th>
        Subject
      </th>
      <th>
        Body
      </th>
    </tr>
  </thred>
  <body>
    <% @messages.each do |message| %>
    <tr>
      <td><%= message.sender.name %></td>
      <td><%= message.subject %></td>
      <td><%= message.body %></td>
    </tr>
    <% end %>
  </body>
</table>

app/views/users/_form.html.erb
<h1> Sign Up!</h1>

<%= form_for @user do |f| %>
<!-- show error when login in user has problem -->
  <% if @user.errors.size > 0 %>
    <div class="alert alert-danger">
      <%= @user.errors.full_messages.to_sentence %>
    </div>
  <% end %>
  <div class="half-width" >
    <%= f.text_field 'name', class: 'form-control', placeholder: 'Name'%>
  </div>

  <div class="half-width" >
    <%= f.text_field 'email', class: 'form-control' , placeholder: 'Email'%>
  </div>

  <div class="half-width" >
    <%= f.password_field 'password', class: 'form-control', placeholder: 'Password'%>
  </div>

  <div class="half-width">
      <%= f.password_field 'password_confirmation', class: 'form-control', placeholder: 'Confirmation' %>
  </div>

  <%= f.submit "Sign Up", class: 'btn btn-secondary' %>
<% end %>

app/views/users/_user.html.erb
<div class="col-xs-12 col-md-4">
  <div class="card card-<%= cycle('male', 'female') %>">
    <%= image_tag user.try(:image_url)unless user.image_url.blank? %>
    <div class="card-block">
      <h4 class="card-title"><%= user.try(:name) %></h4>
      <% if current_user.present? %>
        <a href="#" class="btn btn-primary">Add Friend</a>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container users-index">
  <% @users.in_groups_of(3) do |group| %>
    <div class="row">
      <%= render partial: 'user', collection: group.compact %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render 'users/form' %>